In [2]:
import numpy as np
import matplotlib.pyplot as plt


In [4]:
import numpy as np
import matplotlib.pyplot as plt

def loadData():
    """
    x : time array
    y : matrix of states
    state vector: [x1, x1', x2,x2']
    :return:
    """
    features_num =3
    t = np.arange(1, 50.0,0.5,dtype= float)
    y = np.mat(np.zeros([len(t), features_num]))
    a0 = 1.2
    k0 = 1.1 
    for i in range(1,features_num+1):
        # linear input examples 
        # y[:,i-1] = np.mat( 1*i * np.array(t)+ 1).T
        # movement model
        # formulas:
        #  a(t) = k0^t *a0
        #  y = s(t) = 1/2 *a(t)*t^2
        pass
    # position 
    y[:,0] =((a0 * np.power(np.ones([1,len(t)])*k0,t) * t**2)/2).T  
    # velocity
    y[:,1] = (np.power(np.ones([1,len(t)])*k0,t)* a0 * t).T
    # acceleration
    y[:,2] = (np.power(np.ones([1,len(t)])*k0,t)* a0).T    
    # generate the corresponding state transition matrix
    # and connection matrix
    H = np.mat(np.identity(features_num))
    dt = 0.5
    phi = np.mat([[1,dt,dt**2*k0],
                  [0,1,k0*dt],
                  [0,0,k0]])
    return t, y, H, phi

if __name__ == '__main__':
    x, y, H, phi = loadData()
    print("phi:",phi.shape)
    print("y:",y.shape)


phi: (3, 3)
y: (98, 3)


In [3]:
import numpy as np

def generate_Noise(shape = 4, model = "Gaussian"):

    if model == "Gaussian":
        if shape == 4:
            R = np.mat([  [0.2,0.2,0.2,0.2],
                          [0.2,0.8,0.8,0.2],
                          [0.2,0.8,0.8,0.2],
                          [0.2,0.2,0.2,0.2]])
    
            Q = np.mat([  [0.4,0.4,0.4,0.4],
                          [0.4,0.6,0.6,0.4],
                          [0.4,0.6,0.6,0.4],
                          [0.4,0.4,0.4,0.4]])
        elif shape ==3:
            R = np.mat([ [0.2,0.2,0.2],
                          [0.2,0.5,0.2],
                          [0.2,0.2,0.2]])
    
            Q = np.mat([  [0.3,0.3,0.3],
                          [0.3,0.6,0.3],
                          [0.3,0.3,0.3]])
    elif model == "linear":
        R = np.mat(np.identity(shape) * 0.5)
        Q = np.mat(np.identity(shape) * 0.5)
    return R,Q
if __name__ == '__main__':
    Q,R = generate_Noise(3,"Gaussian")
    print("Q:",Q)
    print("R:",R)


Q: [[ 0.2  0.2  0.2]
 [ 0.2  0.5  0.2]
 [ 0.2  0.2  0.2]]
R: [[ 0.3  0.3  0.3]
 [ 0.3  0.6  0.3]
 [ 0.3  0.3  0.3]]


In [1]:
import numpy as np



if __name__ == '__main__':
    print(np.random.normal(0,0.3,9))
    np.std()
    pass

[ 0.26452424  0.12232664 -0.24640838 -0.23323758 -0.0823557   0.29616689
 -0.52317957 -0.34954714 -0.30817988]
